module.exports = {
  apps: [
    {
      name: 'booknest-backend',
      script: './src/index.ts',
      interpreter: 'npx',
      interpreter_args: 'tsx',
      cwd: '/root/fjr_learn/booknest/backend',
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/logs/booknest-backend-error.log',
      out_file: '/root/logs/booknest-backend-out.log',
    },
    {
      name: 'booknest-worker',
      script: './src/workers/index.ts',
      interpreter: 'npx',
      interpreter_args: 'tsx',
      cwd: '/root/fjr_learn/booknest/backend',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/logs/booknest-worker-error.log',
      out_file: '/root/logs/booknest-worker-out.log',
    },
    {
      name: 'booknest-frontend',
      script: './node_modules/.bin/serve',
      args: ['dist', '-l', '4001', '--single'],
      cwd: '/root/fjr_learn/booknest/frontend',
      instances: 1,
      autorestart: true,
      watch: false,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/logs/booknest-frontend-error.log',
      out_file: '/root/logs/booknest-frontend-out.log',
    },
  ],
}
