/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login": {
    /** 用户登录 */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description 登录成功 */
        200: {
          content: {
            "application/json": {
              code: number;
              message: string;
              data: {
                token: string;
                user: {
                  /** Format: uuid */
                  id: string;
                  /** Format: email */
                  email: string;
                  name: string;
                  /** @enum {string} */
                  role?: "USER" | "ADMIN";
                  /** Format: date-time */
                  createdAt?: string;
                };
              };
            };
          };
        };
        /** @description 参数错误 */
        400: {
          content: {
            "application/json": {
              code: number;
              message: string;
              details?: unknown;
            };
          };
        };
      };
    };
  };
  "/api/v1/books": {
    /** 书籍列表 */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          status?: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
          categoryId?: string;
          search?: string;
          sortBy?: "createdAt" | "updatedAt" | "title";
          sortOrder?: "asc" | "desc";
        };
      };
      responses: {
        /** @description 书籍分页列表 */
        200: {
          content: {
            "application/json": {
              code: number;
              message: string;
              data: {
                items: ({
                    /**
                     * Format: uuid
                     * @example 4e8311a0-8f32-4e9d-a17b-0e9f12345678
                     */
                    id: string;
                    /** @example Clean Code */
                    title: string;
                    /** @example Robert C. Martin */
                    author: string;
                    isbn?: string | null;
                    pageCount?: number | null;
                    description?: string | null;
                    coverUrl?: string | null;
                    /** @enum {string} */
                    status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                    /** Format: uuid */
                    categoryId?: string | null;
                    /** Format: uuid */
                    userId: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  })[];
                total: number;
                page: number;
                pageSize: number;
                totalPages: number;
              };
            };
          };
        };
      };
    };
    /** 创建书籍 */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            title: string;
            author: string;
            isbn?: string;
            pageCount?: number;
            description?: string;
            /** Format: uri */
            coverUrl?: string;
            /**
             * @default WISHLIST
             * @enum {string}
             */
            status?: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
            /** Format: uuid */
            categoryId?: string;
          };
        };
      };
      responses: {
        /** @description 创建成功 */
        201: {
          content: {
            "application/json": {
              code: number;
              message: string;
              data: {
                /**
                 * Format: uuid
                 * @example 4e8311a0-8f32-4e9d-a17b-0e9f12345678
                 */
                id: string;
                /** @example Clean Code */
                title: string;
                /** @example Robert C. Martin */
                author: string;
                isbn?: string | null;
                pageCount?: number | null;
                description?: string | null;
                coverUrl?: string | null;
                /** @enum {string} */
                status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
                /** Format: uuid */
                categoryId?: string | null;
                /** Format: uuid */
                userId: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Book: {
      /**
       * Format: uuid
       * @example 4e8311a0-8f32-4e9d-a17b-0e9f12345678
       */
      id: string;
      /** @example Clean Code */
      title: string;
      /** @example Robert C. Martin */
      author: string;
      isbn?: string | null;
      pageCount?: number | null;
      description?: string | null;
      coverUrl?: string | null;
      /** @enum {string} */
      status: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
      /** Format: uuid */
      categoryId?: string | null;
      /** Format: uuid */
      userId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateBookBody: {
      title: string;
      author: string;
      isbn?: string;
      pageCount?: number;
      description?: string;
      /** Format: uri */
      coverUrl?: string;
      /**
       * @default WISHLIST
       * @enum {string}
       */
      status?: "OWNED" | "READING" | "FINISHED" | "WISHLIST";
      /** Format: uuid */
      categoryId?: string;
    };
    LoginBody: {
      /** Format: email */
      email: string;
      password: string;
    };
    RegisterBody: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
    };
    AuthResponse: {
      token: string;
      user: {
        /** Format: uuid */
        id: string;
        /** Format: email */
        email: string;
        name: string;
        /** @enum {string} */
        role?: "USER" | "ADMIN";
        /** Format: date-time */
        createdAt?: string;
      };
    };
    ErrorResponse: {
      code: number;
      message: string;
      details?: unknown;
    };
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
